version: "3.9"

services:
  # =========================
  # 📌 PostgreSQL
  # =========================
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: closet
      POSTGRES_USER: closet-user
      POSTGRES_PASSWORD: closet_1234
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-net

  # =========================
  # 📌 Redis
  # =========================
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-net

  # =========================
  # 📌 Zookeeper (Kafka 의존)
  # =========================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-net

  # =========================
  # 📌 Kafka Broker
  # =========================
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-net

  # =========================
  # 📌 API 서버 (Spring Boot 8080)
  # =========================
#  api:
#    build: service/sb05-closet-api/closet
#    container_name: closet-api
#    depends_on:
#      - postgres
#      - redis
#      - kafka
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/closet
#      DATABASE_USERNAME: closet-user
#      DATABASE_PASSWORD: closet_1234
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#      JWT_SECRET: 376352270f35f8070b7a7e2ae299ca43
#      BASEURL: http://localhost:3000
#    expose:
#      - 8080
#    networks:
#      - app-net

  # =========================
  # 📌 WS 서버 (Spring Boot 8081)
  # =========================
#  ws:
#    build: service/sb05-closet-sse-ws/closet
#    container_name: closet-ws
#    depends_on:
#      - postgres
#      - redis
#      - kafka
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/closet
#      DATABASE_USERNAME: closet-user
#      DATABASE_PASSWORD: closet_1234
#      REDIS_HOST: redis
#      REDIS_PORT: 6379
#      JWT_SECRET: 376352270f35f8070b7a7e2ae299ca43
#      # WS → API 호출 주소 (Docker 네트워크용)
#      DM_API_BASE_URL: http://closet-api:8080
#    expose:
#      - 8081
#    networks:
#      - app-net

  # =========================
  # 📌 Nginx (Reverse Proxy)
  # =========================
  nginx:
    build: service/sb05-closet-nginx
    container_name: closet-nginx
#    depends_on:
#      - api
#      - ws
    ports:
      - "3000:80"
    networks:
      - app-net
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3030:3000"
    depends_on:
      - prometheus

networks:
  app-net:

volumes:
  postgres-data:
